preset:
  psr2

enabled:
  - concat_without_spaces
  - include
  - lowercase_cast
  - method_separation
  - new_with_braces
  - no_blank_lines_between_uses
  - no_short_echo_tag
  - no_whitespace_before_comma_in_array
  - short_array_syntax
  - short_scalar_cast
  - trailing_comma_in_multiline_array

disabled:
  - blank_line_after_namespace
  - method_argument_space
