language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.4 5.5
      env: setup=lowest
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - phpunit
#  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
