language: php

php:
#  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic
    - secure: "EugH6sDO3qDQCN4Xar9kgGaOzG/KNpUoA6Q4Cum2aOqd39W3cDNkgKndt8uyUqR5ysR4cQn0/Y6Ejk0zbED4bjtyvxBXhemJMCBH2Y9dhvWn6bNS6YARRM5geLEgtYDhOiKdLyd+I8uvsQzqqnqzLpW9I1/OCQmqy9ktyBv9LHhN3yP/6nNPa0gleF5mFwi1Q5k/TWIdqrBuU8JpGQBlv0azi9aaW8yNUnpLffb+BCUe54z4ouAyA3reQtwi2PWvwuEk8t5EybEEDMeIYx+j2a2NKzkLYlxshuQ5j3JMRh7dyrQtpkgtk6r+gcJh8lidmGtDHTTZj6z3vTt/e83ZnUQI3oUCvh5FSQz9ktXxagFq0oR0p3WXF3Uv8AEz0/ZRzF/kjOpciVogI5+mSUTlEVLSnGXQOdtpEv7VKULMQWUOaz/XmGeDEnWledbt6foYqxEQl/h7p8KU5Kacd2u3174Yl+rdcvq//EeVFfdV8biDr3T22P9wFuE3dgzMETtNntEqT3JTnYHtC1NdWqOxAHM4RQCzHFw8oJ9FsyksQ3Edq21Nt9r6H/FGRUMwmlsfQ96b8a6MUFDxPliPgoXObmzOfv5kbKxnj05dXmElQaZ7eXHWctvdiDivGKDgtfF6sHdQ7Fv+/hWxx0tKVJqCLVr4o2f+Tou0oJTbYHUEWB0="
    - secure: "aHdkkVhKXYuDdKqS7aakrr2IuhpeHHofd0lBKV0WT8zGnkoyFl8uQzbzwKHee4JXew4WnMR3QkmrSG7++qO/XRKMyFbDL5l9+mX6tIGUCcwolhfsmfkr+5TIwZhRiU0LcoxKrxSGGwtC/Pja7pgwj639cD8ApjycEaF53N3VWssO+jxmTkugSXx201pngPiro3PHIIS5v+HVjziOu0MJE4Asfpao2TSweyMMr7zi1kqK79aZd2jh514OFkIPkm+w0BXwUcHZVYsy6PIKJ9wsAJwvDY4B/L+RpLR/Z1EDN3uOws9JjfPClSKrt1xjRHEO1ItirR47HeFSKrkFSOkNV9gMOW6i0xJ84tMFMgCd+GoBIv5IwIaetHDT14FhNHWX3VX6BaEFY6Yi9HdVMJYVj/wZ9BbDb5vt/zfvtzxbiJQDB2oiqH8mhE6uIuM6gLtAAkSzGhnDEX9uCvljYkP61YmT9lvf6K6Wty4u/Gf+M55FvjBwaoKAliYN38U/lqUFG3YFE4yaSjfJwgLuK+CI7xpMK0Mc7x/ei8exlEj8nO4igR629fAoKfmKnxjo/OeU0daMkQYLoD9rDeTATwOfDfxFC/ivAX6uzelr4uSirI1K/kAjPZG1yBdt/4QutK4I8w8aJlMGLDmM5wbaWuFUAxx5ioh+VejsdMV8DxAmT9Y="

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.5
      env: setup=lowest
#    - os: linux
#      dist: trusty
#      sudo: required
#    - os: osx
#      osx_image: xcode7.2

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - phpunit
#  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
