language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - SETUP=basic
    - TEST_TRUE=true
    - TEST_FALSE=false
    - TEST_EMPTY=empty
    - TEST_NULL=null
    - TEST_REAL_SEND=false
    # USERNAME
    - secure: "EugH6sDO3qDQCN4Xar9kgGaOzG/KNpUoA6Q4Cum2aOqd39W3cDNkgKndt8uyUqR5ysR4cQn0/Y6Ejk0zbED4bjtyvxBXhemJMCBH2Y9dhvWn6bNS6YARRM5geLEgtYDhOiKdLyd+I8uvsQzqqnqzLpW9I1/OCQmqy9ktyBv9LHhN3yP/6nNPa0gleF5mFwi1Q5k/TWIdqrBuU8JpGQBlv0azi9aaW8yNUnpLffb+BCUe54z4ouAyA3reQtwi2PWvwuEk8t5EybEEDMeIYx+j2a2NKzkLYlxshuQ5j3JMRh7dyrQtpkgtk6r+gcJh8lidmGtDHTTZj6z3vTt/e83ZnUQI3oUCvh5FSQz9ktXxagFq0oR0p3WXF3Uv8AEz0/ZRzF/kjOpciVogI5+mSUTlEVLSnGXQOdtpEv7VKULMQWUOaz/XmGeDEnWledbt6foYqxEQl/h7p8KU5Kacd2u3174Yl+rdcvq//EeVFfdV8biDr3T22P9wFuE3dgzMETtNntEqT3JTnYHtC1NdWqOxAHM4RQCzHFw8oJ9FsyksQ3Edq21Nt9r6H/FGRUMwmlsfQ96b8a6MUFDxPliPgoXObmzOfv5kbKxnj05dXmElQaZ7eXHWctvdiDivGKDgtfF6sHdQ7Fv+/hWxx0tKVJqCLVr4o2f+Tou0oJTbYHUEWB0="
    # PASSWORD
    - secure: "RO3eC+vbCLa+IQpvsgfN62tPt41vtTGEQak7Iiu+2KtUSApz3zmdCymetWBsHHwnooHgmPJb1cyYYsTpdX8dapTsG+Y2VYlxV/hZnCqRIXRChKoZUP3laK5vgotil2EtQa9lxraj4AbfraGtW1owI86aw6kLmxh8dTJQ9J27f8graHzyVTo1dWd0JZrEFtWivF4nM1uERXyostPhfCPsP9kQtwUIFGLJbDPOocAogLwVL+oiBriYWXiNphZexlPxxdpYtYMKntMkOF6AT1pJvj6fFRnl0PNdjCBCJpVGhaQOhsWljrIwoWUNYqgtNUvipLipG1cGGaS0nQXGZgMT7jHQ4OFTkNuZEBbrn7b97E9fMt51MPAONcAUea9/hEaEH3/QC8TpEgyJoY7MpxjmLLW1V8pXW14kBX6XDMZMqsmrifNjhGoEdTU+G/mR37EGcTZO525yo0x8YRBAvJ5QD1MaVo4GhcWNT5Sx+3f1FJXKrP19LHt+Uu+pdUsU9vY00mW3WzRKDmJO9qcovaM1jNFjcsyWY2TxWGi5g4olSQyK/sPUp7N7ryyZTmyWGJnP44PzyGJDsklRiFj7tUYv1+Ur+p5H3yT4apBE72u7o6O6gKsrav/8r8asgS4VWL7E4qqyAkjVujBG8xTn3wMcEC6rmNeVbhLDVeHXw2KKRXE="
    # TEST_MESSAGE_ID
    secure: "cecfsF7lFec14aFYKG/CBgSF9NW2my8f+oB5AOYLRsfYstI6PySkb3nCYjurYyDZnnYfAFRI5QQoVNRxkmqA3Dbq94rexzAd7R2isYcuHkEx0qeEJgQu7jTieLvW+7yUZTqaqxI38kAis5hPBhUBUTJ8vPBAB7EmC/fDwqDKGn+hNioTgZcFr4iZqwbnCcwlGMNW4l/vHa3lDGhYgJ8RYBDiizKNcYVvtbfXAmgOc0BBt/7iEUZOZ2FUZzztXu6OWE0rZ3a+OpF6CCNTvKE5tS8vR/IfHgq1HapGW0XtqEZWK3XrXaWiz1H0RIToUUYYnQd2pUYciYfrIoRfflxjTFvJXTSWvRNx3ue53GODjaLCYtxESxykvD0PNNan2o+H1t1fQAFVY+07bMfvDcXIugWEHSyJ0OfZ/b43DE6OoTJ5TH5hej8CNjy5KG8RlH8s6q/o7b8CQq4PH+nQakmAvi19o+sF7vuFW9DHpTQ/FWgJzygu5Sbe85bBcNlf2akLCbFhSpVnKtdt02IHNSlABafyPJImR7I6vYbgjcT42TDgmVc1l5StfW/ZnE0TgiTIw+n5Jasn6YI7d4pCL7a/rTrDT2ky949AtxSi3JzktQLdaq1q4I/UqOaT2KDN6dg4JB9R07QvbHdRlqQDzmxuGtVm+jGQAtFZlrKyi9UWh0M="

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.4
      env: setup=lowest
    - php: 5.5
      env: setup=lowest
#    - os: osx
#      osx_image: xcode7.2

sudo: false

install:
  - if [[ $SETUP = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - phpunit
  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
