language: php

php:
#  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic
#    - secure: "EugH6sDO3qDQCN4Xar9kgGaOzG/KNpUoA6Q4Cum2aOqd39W3cDNkgKndt8uyUqR5ysR4cQn0/Y6Ejk0zbED4bjtyvxBXhemJMCBH2Y9dhvWn6bNS6YARRM5geLEgtYDhOiKdLyd+I8uvsQzqqnqzLpW9I1/OCQmqy9ktyBv9LHhN3yP/6nNPa0gleF5mFwi1Q5k/TWIdqrBuU8JpGQBlv0azi9aaW8yNUnpLffb+BCUe54z4ouAyA3reQtwi2PWvwuEk8t5EybEEDMeIYx+j2a2NKzkLYlxshuQ5j3JMRh7dyrQtpkgtk6r+gcJh8lidmGtDHTTZj6z3vTt/e83ZnUQI3oUCvh5FSQz9ktXxagFq0oR0p3WXF3Uv8AEz0/ZRzF/kjOpciVogI5+mSUTlEVLSnGXQOdtpEv7VKULMQWUOaz/XmGeDEnWledbt6foYqxEQl/h7p8KU5Kacd2u3174Yl+rdcvq//EeVFfdV8biDr3T22P9wFuE3dgzMETtNntEqT3JTnYHtC1NdWqOxAHM4RQCzHFw8oJ9FsyksQ3Edq21Nt9r6H/FGRUMwmlsfQ96b8a6MUFDxPliPgoXObmzOfv5kbKxnj05dXmElQaZ7eXHWctvdiDivGKDgtfF6sHdQ7Fv+/hWxx0tKVJqCLVr4o2f+Tou0oJTbYHUEWB0="
#    - secure: "RO3eC+vbCLa+IQpvsgfN62tPt41vtTGEQak7Iiu+2KtUSApz3zmdCymetWBsHHwnooHgmPJb1cyYYsTpdX8dapTsG+Y2VYlxV/hZnCqRIXRChKoZUP3laK5vgotil2EtQa9lxraj4AbfraGtW1owI86aw6kLmxh8dTJQ9J27f8graHzyVTo1dWd0JZrEFtWivF4nM1uERXyostPhfCPsP9kQtwUIFGLJbDPOocAogLwVL+oiBriYWXiNphZexlPxxdpYtYMKntMkOF6AT1pJvj6fFRnl0PNdjCBCJpVGhaQOhsWljrIwoWUNYqgtNUvipLipG1cGGaS0nQXGZgMT7jHQ4OFTkNuZEBbrn7b97E9fMt51MPAONcAUea9/hEaEH3/QC8TpEgyJoY7MpxjmLLW1V8pXW14kBX6XDMZMqsmrifNjhGoEdTU+G/mR37EGcTZO525yo0x8YRBAvJ5QD1MaVo4GhcWNT5Sx+3f1FJXKrP19LHt+Uu+pdUsU9vY00mW3WzRKDmJO9qcovaM1jNFjcsyWY2TxWGi5g4olSQyK/sPUp7N7ryyZTmyWGJnP44PzyGJDsklRiFj7tUYv1+Ur+p5H3yT4apBE72u7o6O6gKsrav/8r8asgS4VWL7E4qqyAkjVujBG8xTn3wMcEC6rmNeVbhLDVeHXw2KKRXE="

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.5
      env: setup=lowest
#    - os: linux
#      dist: trusty
#      sudo: required
#    - os: osx
#      osx_image: xcode7.2

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - phpunit
#  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
