language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer install

script:
  - phpunit
#  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
