language: php

php:
#  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic
    - secure: "b1WdkTyfDlj07+QRZdTRFA6MW35AQlFDy0SkSkkS3/8mSCMjgMtB3UbKALjrgu3q1JbB8zDX/FKYSQG/Yq+uaiNEnJHzQwMKpeF7SSirmNRp4mAfj2nfgG2i4FmC6mQgvLIuEdcGOXHgJHLYEF3gVPdwvp26UmqFwpwGhITyzsCxoZR6hiE5TL1wgLgJgbwwoobo2z2AyQK6AIGv8bKA4cRHstvSi4J4/hmSRfnviTK39erj91S/SKBHICmaa7FvFcW9PSwGT+40Zf1YBPKOUG5X4zkpLKLDR9o629mBLuqvV8K5AfY1s3GK0Plw8wdKzM/LMOJEVodJAI0Hacwf1C8F5TPWqL5MDFHNIl71HyO+8EZvKSp1LfHquvVR2EPpdGUj0M2nsR8KTwfHjteqPZN23EiEdIfMVYh0uuKPoO7tzTy0OF6ZQ5E1wrEbPOX4UyNpC8FEphUzhscYXQixlENE8LgVvIpAfz/z4nL+PrRNV+ccGU8CDlJoLU+0rfZ8YLDiHLF3qxigymvv575d3EX4enLzbEGdrIe7aCuE7fAtJ7hTn4KBFy/LP7EW0m3UDRm6zR/OnixP0/orU5FGbt7BwJr/x1apqeqIdpERFj1x/o8Axun11Gn6lSIACOOUe8tF/5czXX8sxb1dzHvj9iC/Y5RGrksddAvVdW1ycUU="
    - secure: "HFtaAYyLh/6s6o+nJjSzvMkjitY52a4tktwIIXZ/PiBXRL6iytVdtmVPqCGhTvTPB5lwgdIui6BXrIy3f44awVVp58PDfrXwZ3DwahLztXI0q87sMGiqaySTqfYlzjBXWr0shw1XZ4GCNk0ZeGo+Lms51zP1WKK6Itf6pBrmesB4H3kJhoXJeRazu4Eee49LUIlNzVDCVi+7TkfvCvmvqihn2BrUBxWNeyLjnu2svWUcz0grtoCvoOyEq3cHr3/FCGCeHbhyrWJfA0hadOOX7/FKY23L5Hfq45jjfYfGMPC8Pu4yM3xw/6wKIAmZ0vPOR5pVsfn0hxGfFvDL4BuniQwnAJX3TNhsrFVGnT0dxDfbC+7afKUQkObvthPyGaLZCxIRLM8kaqZr1E5CbOIXr2McLjuj0fQXu3AaauMF6e+gVNq9qE4/wxelCK94tbDrGz+62SnO2gvIYzGmEjBUibRLcHQANXtVlxfAHuZNW5yv6m8AU+SHGS6XL48zjoyldUfwip6X4r9o9LeMQaylYW+EVDs9jStSZjK2iFgy6InFrxp0f9khleCBuWtbW3Crtrk8AELVRjCaqP65HSeuAdoYS27G+jAHnb9kRE2MphDriwydt5P29lFbjt/aMEg0ksClscpZtRXPYF7ZzCp7hJVj6CINHSoNKUdDLPJ2cYM="

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.5
      env: setup=lowest
#    - os: linux
#      dist: trusty
#      sudo: required
#    - os: osx
#      osx_image: xcode7.2

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - phpunit
#  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
