language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - SETUP=basic
    - TEST_TRUE=true
    - TEST_FALSE=false
    - TEST_EMPTY=empty
    - TEST_NULL=null
    - TEST_REAL_SEND=false
    # TEST_USERNAME
    - secure: "n4F4yhrKhHppIzBH3vuaavmeORUDAukeQ+z9C+ygc3ErtQ6wa+6ih4FfGct9pUzxbpjqZws4Kb+YjLs1m2ewMDQxym04duFNZhzVv9MmrzXiPQFh4TIy+px0HZn4pgpbTnxEPj6uoejvibLL4nQyIbN0n525TaZkgs+aDyEZm78T3HbBLhHyuAaglbDHM5LmwsthGshRbi8sNNLg03NAuXxyj3F2iukxi2UF8vep2ZkYE/yg1/6XBqO7uv0l5/NZkyG0WmmKrvnFtGM9XJWziKEbL0dZ+bzSwx9IMKRo0JvsaSULBiNrS+fiMKd6K/iI2eYpesDrVojyDRfTwX79Kq1xKB8xbj5AuL3ahkrzf9V+iRdEnOODx5f4d4RBfIKDFWYIWJ6cyGDmRIpPymn+ZJgkESxf2iT18q978N3COegeh+96nvOmA8lscFYxvrzyrbOYzEp+UykAURI2aGzbL/r27AzhIcTp0L6u7fuRINDT+Sl5VR5SLOul9a+ZAjcRG6+om82yd588iUxYxD5as1NRu9RblapOitYr86VTgo9hdieAp09aO/SXgRKOvUslxX9mGn+SdJNwROcHRNfrBD8DM97P5Ujrj8DwGKComtf+qf4HTL2y60SbzmiHl8AcCt1on92fRik8lfwmLpb3bLh0F34TDiAUt/zQVklLgLo="
    # TEST_PASSWORD
    - secure: "mmCnGhqkIyo9O4n+QRoGOqI60yuUhrtiOTilfzPbcdacqNe7Fjahg6E9vbhJthKzgQVIjm1SPssjvhSJV4NFnpHPvtKIh7i0MOJyKpMV1dCyfffjh8IVucm8XgtxszJc5fQPT41h6nSVpxEhh7OBGJnlttStu1sE/pvQxc/iNX9eUOkRY/7m8pyed/AOl37QIOmjlFBG9/SzmkPrKKNVBw18gs1CY3I3UjLczuQIADCDVOAq3MnuMJz9udTyyqcR6il85TyN5RkDVJbf6bwX6kc/VadhDZROtVUA2v0EeuvzEjszsDAzmYD52bwevaIwfesdBYW31nKcZH0BUHPERE32smz5dafrbZRHwIPww7bKxwlzyLdkPt/drSEz9mPOlOFJQIKAmcrkyFYBgl0spxk7NoBG+80zwS2D5OhWm/QYPAgUVCW8536EaU+0XnaozoxXVPrAvgXaM5dcCz1JDw2mGxMGgVSrVqDJKMmCIIbW9FPeFHXafbDTPfpCNSlpwNRcbJNSSIU90XzeOYnLg3iEyESw65MBK6qrDqjbsh0gQYLJRANwJB7LbRJEfRBvZsjvh1/4xvbdlS66m/L2aSfgmtzxDGoI4tM7EXMT0WWgtWOt2q7h1iS6UG2ATtPV4E11pq8CHB0OLryjgAgONME9Y0oQFyfjTWCerWR48dg="
    # TEST_MESSAGE_ID
    - secure: "cecfsF7lFec14aFYKG/CBgSF9NW2my8f+oB5AOYLRsfYstI6PySkb3nCYjurYyDZnnYfAFRI5QQoVNRxkmqA3Dbq94rexzAd7R2isYcuHkEx0qeEJgQu7jTieLvW+7yUZTqaqxI38kAis5hPBhUBUTJ8vPBAB7EmC/fDwqDKGn+hNioTgZcFr4iZqwbnCcwlGMNW4l/vHa3lDGhYgJ8RYBDiizKNcYVvtbfXAmgOc0BBt/7iEUZOZ2FUZzztXu6OWE0rZ3a+OpF6CCNTvKE5tS8vR/IfHgq1HapGW0XtqEZWK3XrXaWiz1H0RIToUUYYnQd2pUYciYfrIoRfflxjTFvJXTSWvRNx3ue53GODjaLCYtxESxykvD0PNNan2o+H1t1fQAFVY+07bMfvDcXIugWEHSyJ0OfZ/b43DE6OoTJ5TH5hej8CNjy5KG8RlH8s6q/o7b8CQq4PH+nQakmAvi19o+sF7vuFW9DHpTQ/FWgJzygu5Sbe85bBcNlf2akLCbFhSpVnKtdt02IHNSlABafyPJImR7I6vYbgjcT42TDgmVc1l5StfW/ZnE0TgiTIw+n5Jasn6YI7d4pCL7a/rTrDT2ky949AtxSi3JzktQLdaq1q4I/UqOaT2KDN6dg4JB9R07QvbHdRlqQDzmxuGtVm+jGQAtFZlrKyi9UWh0M="

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.4
      env: SETUP=lowest
    - php: 5.5
      env: SETUP=lowest
#    - os: osx
#      osx_image: xcode7.2

sudo: false

install:
  - if [[ $SETUP = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - phpunit
  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
