language: php

php:
#  - 5.4
#  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic
    - secure: "b1WdkTyfDlj07+QRZdTRFA6MW35AQlFDy0SkSkkS3/8mSCMjgMtB3UbKALjrgu3q1JbB8zDX/FKYSQG/Yq+uaiNEnJHzQwMKpeF7SSirmNRp4mAfj2nfgG2i4FmC6mQgvLIuEdcGOXHgJHLYEF3gVPdwvp26UmqFwpwGhITyzsCxoZR6hiE5TL1wgLgJgbwwoobo2z2AyQK6AIGv8bKA4cRHstvSi4J4/hmSRfnviTK39erj91S/SKBHICmaa7FvFcW9PSwGT+40Zf1YBPKOUG5X4zkpLKLDR9o629mBLuqvV8K5AfY1s3GK0Plw8wdKzM/LMOJEVodJAI0Hacwf1C8F5TPWqL5MDFHNIl71HyO+8EZvKSp1LfHquvVR2EPpdGUj0M2nsR8KTwfHjteqPZN23EiEdIfMVYh0uuKPoO7tzTy0OF6ZQ5E1wrEbPOX4UyNpC8FEphUzhscYXQixlENE8LgVvIpAfz/z4nL+PrRNV+ccGU8CDlJoLU+0rfZ8YLDiHLF3qxigymvv575d3EX4enLzbEGdrIe7aCuE7fAtJ7hTn4KBFy/LP7EW0m3UDRm6zR/OnixP0/orU5FGbt7BwJr/x1apqeqIdpERFj1x/o8Axun11Gn6lSIACOOUe8tF/5czXX8sxb1dzHvj9iC/Y5RGrksddAvVdW1ycUU="
    - secure: "G09xhdWtSBTwUbOOzHsUay78NQbY2nt0XUSIA5RrGIYGn64Ol9XyCFhHRIzKIveHrErfTEWi30rJuznm7/g0/aiayhwV330GUH4jodsuMTAx6akMIf2u1wBJjKum2cKDGlooUxqjQeJa0HpmkG3lFx1+p1EMMIsyjDDt7JqQo5ILAkRuwQGWl0JMF1vQbWzm5i1RcAHP6LbEFWoIONActye7TKYtixzLQloDgEZ+5TuaJUU9GhjjyoHhfJYSLTZ4QYEgNFFQYKv/PW6NfN05HX8WP6N/GoaTIpG1qn1/qROUGKqqOGq00KDuwM3mqr5YWKGU5Ov6DKQU8v8jFMFXYRoDYSZAQIVMLQqLI/uTbMefx0jadX7x8ijf2w1LAA0Dmih70v0PngSFJws1UXKjOVc3S/abg8Q2aX1SdITlEU5x5FnZdModRYi5aFybptkDEqpvmxS2EWyRyP0qzaBQNSdKp2dLUcUNePoEeDARaGvAb/eM0qDPbNmQQ5OJuTr8Np42NcG2vUzG9eBYwsXz8CEg57gR7fUTSXLeuQxGazooWq6DcKPjsKuVgW8LFxo8IBhPNa1VLJgOmJIyiGEo3XhQhj0h+1qNz4alXKI78Y32QOak5IbGaRIr/ZTvDETIuhYgV01HdL+qs38FrQvkOHQaZy9nURHKIfs/FtCt6CE="

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.4 5.5
      env: setup=lowest
#    - os: linux
#      dist: trusty
#      sudo: required
#    - os: osx
#      osx_image: xcode7.2

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - phpunit
#  - php ./phpunit/coverage-check.php ./phpunit/clover.xml 80
